# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    pull_request:
        branches: ['*']
        types:
            - opened
            - synchronize
            - closed
    push:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 20.x
              uses: actions/setup-node@v1
              with:
                  node-version: 20.x
            - run: npm ci
            - name: eslint
              run: npm run lint:ci

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 20.x
              uses: actions/setup-node@v1
              with:
                  node-version: 20.x
            - run: npm ci
            - run: npx tsc
            - run: npm run build

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 20.x
              uses: actions/setup-node@v1
              with:
                  node-version: 20.x
            - run: npm ci
            - run: npm test
